//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cardex
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public int Price { get; set; }
        public string Inventory { get; set; }
        public string Place1 { get; set; }
        public string Place2 { get; set; }
        public int MinNumber { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
        public int OrderNumber { get; set; }
        public int ProductID { get; set; }
    }
}
