//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string FactorKind { get; set; }
        public string Description { get; set; }
        public string Transport { get; set; }
        public int TransportPrice { get; set; }
        public int TotalPrice { get; set; }
    }
}
