//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorProducts
    {
        public int ID { get; set; }
        public int FactorID { get; set; }
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int Number { get; set; }
        public int UnitPrice { get; set; }
        public Nullable<int> OfferPrice { get; set; }
        public int TotalPrice { get; set; }
    }
}
