//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Navik_DBEntities : DbContext
    {
        public Navik_DBEntities()
            : base("name=Navik_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<Receipt> Receipt { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Cardex> Cardex { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
    }
}
