//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int LoginID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> InsuranceCost { get; set; }
        public Nullable<int> OverTime { get; set; }
        public Nullable<int> AllowedMonthlyHours { get; set; }
        public Nullable<int> AllowedDailyHours { get; set; }
        public Nullable<int> Delay { get; set; }
        public Nullable<int> Vacation { get; set; }
    }
}
