//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons
    {
        public int PersonID { get; set; }
        public string Grouping { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string NationalID { get; set; }
        public string CompanyID { get; set; }
        public string EconomicCode { get; set; }
        public string Adress { get; set; }
        public Nullable<int> PostalCode { get; set; }
    }
}
